version: '3.7'
services:
  frontend:
    container_name: vuejs-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn serve"